language: cpp
sudo: false
dist: bionic

addons:
  apt:
    packages:
    - meson
    - clang-format

compiler:
  - clang
  - gcc

script:
  - meson builddir
  - cd builddir
  - ninja
  - ninja test
  - ninja clang-format
